version: '3.1'

networks:
  stockbotnet:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
          ip_range: 172.18.1.0/24
          gateway: 172.18.1.1

services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockbot
    networks:
      stockbotnet:
        ipv4_address: 172.18.1.3
        aliases:
          - stockbot-mysql
    healthcheck:
      test: mysql -h 127.0.0.1 -uroot -proot stockbot -e 'select 1'
      interval: 5s
      timeout: 5s
      retries: 100

  stockbot:
    container_name: stockbot
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - "../:/apps/stockbot:Z"
    build:
      context: ../
      dockerfile: docker/stockbot.dockerfile
    networks:
      stockbotnet:
        ipv4_address: 172.18.1.4
        aliases:
          - stockbot-worker